package com.example.upproject;

import java.util.HashMap;

public class MapActivity {
    public static HashMap<String, Integer> map = new HashMap<String, Integer>(26);
    public static HashMap<String, String> language = new HashMap<String, String>(300);
    static {
        //language recognition
        //code language with tag and name
        language.put("af","Afrikaans");
        language.put("am","Amharic");
        language.put("ar","Arabic");
        language.put("ar-Latn","Arabic");
        language.put("az","Azerbaijani");
        language.put("be","Belarusian");
        language.put("bg","Bulgarian");
        language.put("bg-Latin","Bulgarian");
        language.put("bn","Bengali");
        language.put("bs","Bosnian");
        language.put("ca","Catalan");
        language.put("ceb","Cebuano");
        language.put("co","Corsican");
        language.put("cs","Czech");
        language.put("cy","Welsh");
        language.put("da","Danish");
        language.put("de","German");
        language.put("el","Greek");
        language.put("el-Latin","Greek");
        language.put("en","English");
        language.put("eo","Esperanto");
        language.put("es","Spanish");
        language.put("et","Estonian");
        language.put("eu","Basque");
        language.put("fa","Persian");
        language.put("fi","Finnish");
        language.put("fil","filipino");
        language.put("fr","French");
        language.put("fy","Western Frisian");
        language.put("ga","Irish");
        language.put("gd","Scots Gaelic");
        language.put("gl","Galician");
        language.put("gu","Gujarati");
        language.put("ha","Hausa");
        language.put("haw","Hawaiian");
        language.put("he","Hebrew");
        language.put("hi","Hindi");
        language.put("hi-Latn","Hindi");
        language.put("hmn","Hmong");
        language.put("hr","Croatian");
        language.put("ht","Haitian");
        language.put("hu","Hungarian");
        language.put("hy","Armenian");
        language.put("id","Indonesian");
        language.put("ig","Igbo");
        language.put("is","Icelandic");
        language.put("it","Italian");
        language.put("ja","Japanese");
        language.put("ja-Latin","Japanese");
        language.put("jv","Javaense");
        language.put("ka","Geogian");
        language.put("kk","Kazakh");
        language.put("km","Khmer");
        language.put("kn","Kannada");
        language.put("ko","Korean");
        language.put("ku","Kurdish");
        language.put("ky","Kyrgyz");
        language.put("la","Latin");
        language.put("lb","Luxembourgish");
        language.put("lo","Lao");
        language.put("lt","Lithuanian");
        language.put("lv","Latvian");
        language.put("mg","Malagasy");
        language.put("mi","Maori");
        language.put("mk","Macedonian");
        language.put("ml","Malayalam");
        language.put("mn","Mongolian");
        language.put("mr","Marathi");
        language.put("ms","Malay");
        language.put("mt","Maltese");
        language.put("my","Burmese");
        language.put("ne","Nepali");
        language.put("nl","Dutch");
        language.put("no","Norwegian");
        language.put("ny","Nyanja");
        language.put("pa","Punjabi");
        language.put("pl","Polish");
        language.put("ps","Pashto");
        language.put("pt","Portuguese");
        language.put("ro","Romanian");
        language.put("ru","Russian");
        language.put("ru-Latn","Russian");
        language.put("sd","Sindhi");
        language.put("si","Sinhala");
        language.put("sk","Slovak");
        language.put("sl","Slovenian");
        language.put("sm","Samoan");
        language.put("sn","Shona");
        language.put("so","Somali");
        language.put("sq","Albanian");
        language.put("sr","Serbian");
        language.put("st","Sesotho");
        language.put("su","Sundanese");
        language.put("sv","Swedish");
        language.put("sw","Swahili");
        language.put("ta","Tamil");
        language.put("te","Telugu");
        language.put("tg","Tajik");
        language.put("th","Thai");
        language.put("tr","Turkish");
        language.put("uk","Ukrainian");
        language.put("ur","Urdu");
        language.put("uz","Uzbek");
        language.put("vi","Vietnamese");
        language.put("xh","Xhosa");
        language.put("yi","Yiddish");
        language.put("yo","Yoruba");
        language.put("zh","Chinese");
        language.put("zh-Latn","Chinese");
        language.put("zu","Zulu");

    }
    public static int[] alphabets = {R.drawable.a, R.drawable.b, R.drawable.c, R.drawable.d, R.drawable.e, R.drawable.f, R.drawable.g, R.drawable.h, R.drawable.i, R.drawable.j, R.drawable.k, R.drawable.l, R.drawable.m, R.drawable.n, R.drawable.o, R.drawable.p, R.drawable.q, R.drawable.r,R.drawable.s,R.drawable.t,R.drawable.u,R.drawable.v,R.drawable.w,R.drawable.x,R.drawable.y,R.drawable.z};
        public static int[] digit={R.drawable.zero,R.drawable.one,R.drawable.two,R.drawable.three,R.drawable.four,R.drawable.five,R.drawable.six,R.drawable.seven,R.drawable.eight,R.drawable.ninee};
    public static void main(String[] args) {

        map.put("a", R.drawable.a);
        map.put("b", R.drawable.b);
        map.put("c", R.drawable.c);
        map.put("d", R.drawable.d);
        map.put("e", R.drawable.e);
        map.put("f", R.drawable.f);
        map.put("g", R.drawable.g);
        map.put("h", R.drawable.h);
        map.put("i", R.drawable.i);
        map.put("j", R.drawable.j);
        map.put("k", R.drawable.k);
        map.put("l", R.drawable.l);
        map.put("m", R.drawable.m);
        map.put("n", R.drawable.n);
        map.put("o", R.drawable.o);
        map.put("p", R.drawable.p);
        map.put("q", R.drawable.q);
        map.put("r", R.drawable.r);
        map.put("s", R.drawable.s);
        map.put("t", R.drawable.t);
        map.put("u", R.drawable.u);
        map.put("v", R.drawable.v);
        map.put("w", R.drawable.w);
        map.put("x", R.drawable.x);
        map.put("y", R.drawable.y);
        map.put("z", R.drawable.z);


        //language recognition
        //code language with tag and name
       /* language.put("af","Afrikaans");
        language.put("am","Amharic");
        language.put("ar","Arabic");
        language.put("ar-Latn","Arabic");
        language.put("az","Azerbaijani");
        language.put("be","Belarusian");
        language.put("bg","Bulgarian");
        language.put("bg-Latin","Bulgarian");
        language.put("bn","Bengali");
        language.put("bs","Bosnian");
        language.put("ca","Catalan");
        language.put("ceb","Cebuano");
        language.put("co","Corsican");
        language.put("cs","Czech");
        language.put("cy","Welsh");
        language.put("da","Danish");
        language.put("de","German");
        language.put("el","Greek");
        language.put("el-Latin","Greek");
        language.put("en","English");
        language.put("eo","Esperanto");
        language.put("es","Spanish");
        language.put("et","Estonian");
        language.put("eu","Basque");
        language.put("fa","Persian");
        language.put("fi","Finnish");
        language.put("fil","filipino");
        language.put("fr","French");
        language.put("fy","Western Frisian");
        language.put("ga","Irish");
        language.put("gd","Scots Gaelic");
        language.put("gl","Galician");
        language.put("gu","Gujarati");
        language.put("ha","Hausa");
        language.put("haw","Hawaiian");
        language.put("he","Hebrew");
        language.put("hi","Hindi");
        language.put("hi-Latn","Hindi");
        language.put("hmn","Hmong");
        language.put("hr","Croatian");
        language.put("ht","Haitian");
        language.put("hu","Hungarian");
        language.put("hy","Armenian");
        language.put("id","Indonesian");
        language.put("ig","Igbo");
        language.put("is","Icelandic");
        language.put("it","Italian");
        language.put("ja","Japanese");
        language.put("ja-Latin","Japanese");
        language.put("jv","Javaense");
        language.put("ka","Geogian");
        language.put("kk","Kazakh");
        language.put("km","Khmer");
        language.put("kn","Kannada");
        language.put("ko","Korean");
        language.put("ku","Kurdish");
        language.put("ky","Kyrgyz");
        language.put("la","Latin");
        language.put("lb","Luxembourgish");
        language.put("lo","Lao");
        language.put("lt","Lithuanian");
        language.put("lv","Latvian");
        language.put("mg","Malagasy");
        language.put("mi","Maori");
        language.put("mk","Macedonian");
        language.put("ml","Malayalam");
        language.put("mn","Mongolian");*/

    }
}
